### ISSUE TITLE
Disconnect if using sleeping bag during day

### ISSUE THREAD

**Issue by murapix** [shadowfacts/SleepingBag#6]
Using the modpack Safety Lost v0.2.2. Using the sleeping bag when it isn't night will cause the player to be instantly disconnected from the server.

**Comment by shadowfacts** [comment]
Can you post the log from both the client and the server when trying to sleep during the day?

**Comment by Catphalem** [comment]
I also get disconnected if I attempt to sleep with Sleeping Bag in the situations like when it's not possible to sleep with normal beds.

Ex. During daytime and when mobs are around you.

I've uploaded my log on Dropbox, because of the character limit of 512 at Pastebin.
https://www.dropbox.com/s/d7ypmnf62bcqdvu/2016-10-02-3.log?dl=0

**Comment by shadowfacts** [comment]
Fixed in ShadowMC 3.4.8 ([on CurseForge](https://minecraft.curseforge.com/projects/shadowmc/files/2333812), currently pending approval).
