### ISSUE TITLE
Issue: getting stuck in sleeping bag.

### ISSUE THREAD

**Issue by Kaisoul** [shadowfacts/SleepingBag#8]
In my Lan world i get stuck in the sleeping bag and can not get out unless i restart my world.

only other mod i use that messes with sleeping is Morpheus.

Minecraft 1.10.2
forge 1.10.2-12.18.2.2119
SleepingBag-1.10.2-1.3.0
Morpheus-1.10.2-3.1.9

note that beds work with out issues only the sleeping bag causes this problem.

**Comment by shadowfacts** [comment]
Can you post the `fml-client-latest.log` on a [Gist](https://gist.github.com)?

**Comment by Kaisoul** [comment]
can try to find the log

**Comment by Kaisoul** [comment]
FML latest log (Kaisoul666's gist)
https://gist.github.com/Kaisoul/d4e8ea25a873412d7568c640bde0716e

just copied the file to gist

**Comment by gr8pefish** [comment]
Looks like your log was cut off. The only information in there currently is initialization stuff, it doesn't say anything about when you are stuck.

**Comment by Kaisoul** [comment]
didn't notice that it cut off that log... sad to say i have no clue what
log to find now -_- im very bad at finding non-crash logs

**Comment by gr8pefish** [comment]
So I was mistaken, gist just cut off the file, you did upload the whole thing; my bad. That being said, there wasn't any useful information in there to help us solve this.

Okay, so what you are going to do is the following:
- If you can reliably reproduce the bug, go into your LAN world and do so.  As soon as the bug occurs (right after it, and not before), you can do two things.
1. You can make sure the console is enabled when launching the game, and just copy paste everything there using gist/pastebin/hastebin/some similar service and linking that here.
2. You can go to the run directory and look at ./logs/latest.log (the client) and fml-server-latest.log (the server) and once again get us access to those.

Also, tell us _exactly_ what happened so that we can try and duplicate/understand the error. It would be difficult for you to provide too much information ;)

Thanks!

**Comment by gr8pefish** [comment]
Any update? If we don't ever hear back the issue will be closed.

**Comment by shadowfacts** [comment]
Closing this due to lack of response.
